# Generated by Django 3.2.5 on 2021-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('pl', models.CharField(max_length=255, verbose_name='PL')),
                ('kyomei_level', models.IntegerField(default=1, verbose_name='共鳴レベル')),
                ('kyomei_omote', models.CharField(max_length=255, verbose_name='共鳴感情(表)')),
                ('kyomei_ura', models.CharField(max_length=255, verbose_name='共鳴感情(裏)')),
                ('kyomei_root', models.CharField(max_length=255, verbose_name='共鳴感情(ルーツ)')),
                ('shintai', models.IntegerField(verbose_name='身体')),
                ('kiyou', models.IntegerField(verbose_name='器用')),
                ('seishin', models.IntegerField(verbose_name='精神')),
                ('gokan', models.IntegerField(verbose_name='語感')),
                ('chiryoku', models.IntegerField(verbose_name='知力')),
                ('miryoku', models.IntegerField(verbose_name='魅力')),
                ('shakai', models.IntegerField(verbose_name='社会')),
                ('unsei', models.IntegerField(verbose_name='運勢')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.CharField(max_length=255, verbose_name='性別')),
                ('occupation', models.CharField(max_length=255, verbose_name='職業')),
                ('shusshin', models.CharField(max_length=255, verbose_name='出身')),
                ('hp', models.IntegerField(verbose_name='HP')),
                ('mp', models.IntegerField(verbose_name='MP')),
                ('chat_pallet', models.CharField(max_length=255, verbose_name='チャパレ')),
            ],
        ),
    ]
